### ISSUE TITLE
can it decode sony 360-reality-audio ?

### ISSUE THREAD

**Issue by serious-snow** [ittiam-systems/libmpegh#5] opened 2022-06-06 03:03 UTC
sony 360-reality-audio based on MPEG-H 3D audio.but i can't decode it 

it shows "fatal error: Ittiam mpegh_dec  core coder module :Initialization: : Initialization fatal error"

**Comment by SakethSathuvalli** [comment] 2022-06-06 03:27
Hi,

Will it be possible to share the stream with us?
This can help us find the exact reason for the initialization failure!

Thanks!

**Comment by serious-snow** [comment] 2022-06-06 05:28
https://drive.google.com/file/d/1vGPje25oqB-KFobcbQl8HlIguwL-o7Jn/view?usp=sharing

thanks,it download from tencent QQ music

**Comment by serious-snow** [comment] 2022-06-06 05:29
I don't know  it whether be encrypted

**Comment by AnnshaMerlin** [comment] 2022-06-06 06:46
Thanks for sharing the stream!

We have downloaded the stream and looked into the cause for the decoding failure. We found that the stream parameter indicates that it is Low Complexity profile level 4. Our decoder supports upto Low Complexity profile level 3.

However, it can be decoded with our decoder with a simple workaround. The workaround solution is to comment line number [1483](https://github.com/ittiam-systems/libmpegh/blob/6094c0bfe4e2d4c89ee2e0c6a88bb88c344a9ef4/decoder/ia_core_coder_init_config.c#L1483) in [libmpegh/decoder/ia_core_coder_init_config.c](https://github.com/ittiam-systems/libmpegh/blob/main/decoder/ia_core_coder_init_config.c) , rebuild our decoder and run again. We tested this hack at our end and the stream is decoding fine.

Hope this helps!

Thanks,
Annsha

**Comment by serious-snow** [comment] 2022-06-06 07:21
Thanks very much ,it was decoded successfully.
But I still can't play it by ffmpeg or other player.
Anyway, it's better than before.

**Comment by AnnshaMerlin** [comment] 2022-06-06 09:06
Can you try changing audio settings in VLC and try once.
Initially we also couldn't play and we did this.

![image](https://user-images.githubusercontent.com/89138078/172129938-3e913f58-bc87-4a3c-8218-81e05a21b130.png)

**Comment by serious-snow** [comment] 2022-06-06 09:20
Yes,it was work!
Thanks again!

**Comment by AnnshaMerlin** [comment] 2022-06-06 09:29
Could you please close this issue?

**Closed** 2022-06-06 09:30 UTC

**Comment by D3rel** [comment] 2022-08-31 06:51
> Hi,
> 
> Will it be possible to share the stream with us? This can help us find the exact reason for the initialization failure!
> 
> Thanks!

Hi! Can you analyze this file and tell me what's going on, or if this tool can decode this type of file... or if any adjustments need to be done for this. I'm getting the message: _"fatal error: Ittiam mpegh_dec core coder module :Initialization: : Initialization fatal error"_

Well, I've been using your tool for a while, it's great and it's working perfectly for 22.2 audios (LC@L4) after I modified the file _ia_core_coder_init_config.c_ following the instructions given by the message from AnnshaMerlin. But this mod is not working for this file.

**DL** | http://opus-techzboy.herokuapp.com/73108/1-01.+Losing+Grip.m4a?hash=AgADNg

**Mediainfo:**
```
Format                      : MPEG-4
Format profile              : Base Media / Version 1
Codec ID                    : mp41 (iso8/isom/mp41/dash/cmfc)
File size                   : 44.0 MiB
Duration                    : 3 min 50 s
Overall bit rate            : 1 603 kb/s
Encoded date                : UTC 2022-06-15 20:47:25
Tagged date                 : UTC 2022-06-15 20:47:25

Audio
ID                          : 1
Format                      : MPEG-H 3D Audio
Format profile              : LC@L4
Codec ID                    : mha1
Duration                    : 3 min 50 s
Bit rate                    : 1 599 kb/s
Channel(s)                  : 24 channels (22.2)
Channel layout              : Lw Rw C LFE Lb Rb L R Cb LFE2 Lss Rss Tfl Tfr Tfc Tc Tbl Tbr Tll Tsr Tbc Bfc Bfl Bfr
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Stream size                 : 43.9 MiB (100%)
Encoded date                : UTC 2022-06-15 20:47:25
Tagged date                 : UTC 2022-06-15 20:47:25
Signal group #1             : 12 objects
 Type                       : Object
 Number of objects          : 12 objects
Codec configuration box     : mhaC
```

What I could notice of difference between the files that the tool can decode for this one, is the codec. It's working for: 
```
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (mp42/isom)
```

Thanks in advance :)
