### ISSUE TITLE
Unable to decode fragmented mhm1 mp4 file

### ISSUE THREAD

**Issue by miartad** [ittiam-systems/libmpegh#60] opened 2023-06-27 09:04 UTC
Hello,

I have used Bento4 (https://github.com/axiomatic-systems/Bento4) tools to fragment mha1 and mhm1 files. MHA1 is decode-able but MHM1 fails to decode, is this expected?

Original files used are both decode-able:

```
as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mha1.mp4
as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mhm1.mp4
```

then with Bento4:

```
mp4fragment as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mha1.mp4 fragmented.mha1.mp4
mp4fragment as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mhm1.mp4 fragmented.mhm1.mp4
```

Generated fragmented MHA1 file is playable, fragmented MHM1 file is not playable with error:

```
./ia_mpeghd_testbench -ifile:fragmented.mhm1.mp4.txt -ofile:test.wav
-ifile:fragmented.mhm1.mp4.txt -ofile:test.wav
                       ITTIAM SYSTEMS PVT LTD, BANGALORE
                             http:\\www.ittiam.com
                      IA_MPEG_H_3D_AUD_DEC_X86 $Rev: 1.2 $


non fatal error: Ittiam mpegh_dec  core coder module :Initialization: : Insufficient input bytes
```

Attached the files.

[fragmented.mhm1.mp4.txt](https://github.com/ittiam-systems/libmpegh/files/11879876/fragmented.mhm1.mp4.txt)
[fragmented.mha1.mp4.txt](https://github.com/ittiam-systems/libmpegh/files/11879877/fragmented.mha1.mp4.txt)
[as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mhm1.mp4.txt](https://github.com/ittiam-systems/libmpegh/files/11879878/as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mhm1.mp4.txt)
[as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mha1.mp4.txt](https://github.com/ittiam-systems/libmpegh/files/11879879/as02_96.wav-8ch-48000kHz.wav-14-5.2.1cicp.mha1.mp4.txt)

Adam

**Comment by SakethSathuvalli** [comment] 2023-06-30 12:13
Hi @miartad 

Thanks for sharing the streams and details of the software used to generate the same.!
We will check this and get back to you at the earliest.

Thanks!

**Comment by Vamsi100858** [comment] 2023-07-24 12:09
Hi @miartad 

Can you please try with the fix available on https://github.com/ittiam-systems/libmpegh/tree/fix-fmp4-mhm1-dec-fail .

**Comment by miartad** [comment] 2023-07-24 12:21
Hi @Vamsi100858,

thank you for the update. I'm no longer working on this but I believe [benjamin-weiss](https://github.com/benjamin-weiss?tab=repositories) is tracking this so he might look into it soon.

**Comment by SakethSathuvalli** [comment] 2023-10-13 11:05
Closing this since the latest main is able to decode these streams.

**Closed by SakethSathuvalli** 2023-10-13 11:05 UTC

**Comment by benjamin-weiss** [comment] 2023-10-18 12:45
We already confirmed that the fix works a long time ago, but I never provided the feedback here. Sorry.
